Repository kubernetes-sigs/container-object-storage-interface, pull requests merged in 2025-04, with the labels that each got.

#21 fix: add wildcard dirs to dependabot
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, size/S

#36 fix: add pages enablement
  .github/workflows/docs.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm

#45 dependabot: add ok-to-test label to PRs automatically
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test
