Repository kubernetes-sigs/container-object-storage-interface, pull requests merged in 2025-01, with the labels that each got.

#6 clean up makefile and CI targets
  Makefile
  hack/cloudbuild.sh
  hack/prow-check-generate.sh
  hack/prow-e2e.sh
Labels: approved, cncf-cla: yes, size/L, lgtm

#2 chore: drop namespace for cluster scoped resources
  controller/resources/rbac.yaml
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#7 cloudbuild: do not run make build in parallel
  hack/cloudbuild.sh
Labels: approved, cncf-cla: yes, size/XS, lgtm

#11 build: fix repo reference in dockerfiles
  hack/Dockerfile.in
Labels: approved, cncf-cla: yes, size/XS, lgtm

#13 cloudbuild: update tag/release script
  hack/cloudbuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#14 Sync main -> release-0.2
  hack/Dockerfile.in
  hack/cloudbuild.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
